{{ if and .Values.skLdap.enabled .Values.skLdap.exposure.external.enabled .Values.skLdap.exposure.external.ingress.enabled }}
{{ if  eq .Values.ingressClass "nginx" }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "skLdap.ingressName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  annotations:
    # We want flow to be secured up to the end. (This option does not prevent plain HTTP if so configured).
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ required "ingress.host must be defined!" .Values.skLdap.exposure.external.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "skLdap.serviceName" . }}
                port:
                  number: {{ ternary 443 80 .Values.skLdap.exposure.external.ssl }}
            path: /
            pathType: Prefix
{{ end }}
{{ end }}
