site_name: SKAS

nav:
  - Home: index.md
  - Installation: installation.md
  - "User guide": userguide.md
  - "Configuration": configuration.md
  - "Architecture": architecture.md
  - "Advanced configuration": advancedconfiguration.md
  - "DEX integration": dex.md
  - "Tools and Tricks": toolsandtricks.md
theme:
  name: readthedocs