site_name: SKAS

nav:
  - Home: index.md
  - Installation: installation.md
  - "Admin guide": adminguide.md
  - "Configuration": configuration.md
  - "LDAP Setup": ldap.md
  - "Identity Providers chaining": chaining.md
  - "Architecture": architecture.md
  - "Advanced configuration": advancedconfiguration.md
  - "DEX integration": dex.md
  - "Tools and Tricks": toolsandtricks.md
theme:
  name: readthedocs