---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sk-static.usersDbName" . }}
  labels:
    {{- include "sk-static.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  users.yaml: |
    {{- with .Values.usersDb.users }}
    users:
      {{- range . }}
      - {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- with .Values.usersDb.groupBindings }}
    groupBindings:
      {{- range . }}
      - {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
