# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - sh -c "cd sk-clientgo && go mod download"
    - sh -c "cd helm && rm -r dist"
    - sh -c "cd helm && helm package -d ./dist skas"
    - sh -c "cd helm && helm package -d ./dist skusers"
    - sh -c "cd ansible/roles && tar cvzf ../../dist/skas-apiserver-role-{{ .Tag }}.tgz skas-apiserver/"
    - sh -c "cd ansible/roles && tar cvzf ../../dist/skas-chart-role-{{ .Tag }}.tgz skas-chart/"
    - sh -c "cd ansible/roles && tar cvzf ../../dist/skusers-role-{{ .Tag }}.tgz skusers/"
builds:
  - id: sk-clientgo
    binary: kubectl-sk
    dir: sk-clientgo
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  prerelease: true
  extra_files:
    - glob: helm/dist/*
archives:
  - format: binary
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
