# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - sh -c "cd sk-clientgo && go mod download"
    - sh -c "cd extra && rm -rf dist"
    - sh -c "cd extra/helm && helm package -d ../dist skas"
    - sh -c "cd extra/helm && helm package -d ../dist skusers"
    - sh -c "cd extra/ansible/roles && tar cvzf ../../dist/skas-apiserver-role-{{ .Tag }}.tgz skas-apiserver/"
builds:
  - id: sk-clientgo
    binary: kubectl-sk
    dir: sk-clientgo
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
release:
  prerelease: true
  extra_files:
    - glob: extra/dist/*
archives:
  - format: binary
    rlcp: true
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
