{{ if .Values.skPadl.enabled  }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skPadl.serviceName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "skas.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ ternary 636 389 .Values.skPadl.exposure.ssl }}
      targetPort: {{ include "skPadl.pod.port" . }}
{{ end }}
