{{ if or .Values.skAuth.enabled .Values.skCrd.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "skas.serviceAccountName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{- end }}