
{{/*
Expand skMerge container
*/}}
{{- define "container.skMerge" -}}
- name: sk-merge
  command:
    - /sk-merge
  args:
    - --configFile
    - /config.yaml
    {{-  range .Values.skMerge.additionalArgs }}
    - {{ . }}
    {{- end }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- with .Values.skMerge.extraEnv }}
  env:
    {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.skMerge.resources }}
  resources:
  {{- toYaml . | nindent 12 }}
  {{ end }}
  securityContext:
    {{- toYaml .Values.commonContainerSecurityContext | nindent 12 }}
    {{- with .Values.skMerge.securityContext }}
    {{- toYaml . | nindent 12 }}
    {{- end }}
  ports:
    - containerPort: {{ .Values.skMerge.serverPort }}
      name: proto
      protocol: TCP
  volumeMounts:
    - mountPath: /config.yaml
      name: sk-merge-config
      subPath: config.yaml
    {{ if and .Values.skMerge.exposure.enabled .Values.skMerge.exposure.ssl }}
    - mountPath: /tmp/cert/server
      name: sk-merge-server-cert
      readOnly: true
    {{ end }}
{{- end }}


{{/*
Expand slMerge volumes in pod
*/}}
{{- define "volumes.skMerge" -}}
- name: sk-merge-config
  configMap:
    name: {{ include "skMerge.configmapName" . }}
{{- if and .Values.skMerge.exposure.enabled .Values.skMerge.exposure.ssl }}
- name: sk-merge-server-cert
  secret:
    defaultMode: 420
    secretName: {{ include "skMerge.certificateSecretName" . }}
{{- end }}

{{- end }}
