{{ if .Values.skLdap.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skLdap.configmapName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    log:
      mode: {{ default .Values.log.mode .Values.skLdap.log.mode }}
      level: {{ default .Values.log.level .Values.skLdap.log.level }}
    servers:
      {{- if .Values.skLdap.exposure.internal.enabled}}
      - port: {{ .Values.skLdap.exposure.internal.port }}
        interface: "127.0.0.1"
        ssl: false
        services:
          identity:
            disabled: {{ .Values.skLdap.exposure.internal.services.identity.disabled }}
            clients: {{ .Values.skLdap.exposure.internal.services.identity.clients | toJson }}
      {{- end }}
      {{- if .Values.skLdap.exposure.external.enabled}}
      - port: {{ .Values.skLdap.exposure.external.port }}
        interface: "0.0.0.0"
        ssl: {{ .Values.skLdap.exposure.external.ssl }}
        {{- if .Values.skLdap.exposure.external.ssl }}
        certDir: /tmp/cert/server
        {{- end }}
        services:
          identity:
            disabled: {{ .Values.skLdap.exposure.external.services.identity.disabled }}
            clients: {{ .Values.skLdap.exposure.external.services.identity.clients  | toJson }}
      {{- end }}
    ldap:
{{ .Values.skLdap.ldap | toYaml | indent 6 }}

{{ end }}

