

{{- range .Values.groupBindings }}
---
apiVersion: userdb.skasproject.io/v1alpha1
kind: GroupBinding
metadata:
  name: {{ (printf "%s-%s" .user .group) | replace ":" "-" }}
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "skusers.labels" $ | nindent 4 }}
spec:
  user: {{ .user }}
  group: {{ .group }}
{{- end }}
