{{- range .Values.generatedSecrets }}
---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ .secretName }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  fields:
{{- range .fields }}
    - fieldName: {{ .name }}
      encoding: {{ .encoding | default "base64" }}
      length: "{{ .length | default 15 }}"
{{- end }}
{{- end }}


