{{ if and .Values.skStatic.enabled .Values.skStatic.exposure.external.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "skStatic.serviceName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "skas.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ ternary 443 80 .Values.skStatic.exposure.external.ssl }}
      targetPort: {{ .Values.skStatic.exposure.external.port }}
{{ end }}
