---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sk-auth.deploymentName" . }}
  labels:
    {{- include "sk-auth.labels" . | nindent 4 }}
  annotations:
    {{ if not .Values.goinkube.enabled }}
    configmap.reloader.stakater.com/reload: "{{ include "sk-auth.configName" . }}"
    {{ end }}
  {{- with .Values.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sk-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sk-auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sk-auth
          {{- if .Values.goinkube.enabled }}
          image: "{{ .Values.goinkube.image.repository }}:{{ .Values.goinkube.image.tag }}"
          imagePullPolicy: {{ .Values.goinkube.image.pullPolicy }}
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /sk-auth
          args:
            - --configFile
            - /config.yaml
          {{-  range .Values.additionalArgs }}
            - {{ . }}
          {{- end }}
          {{ end }}
          {{- if and (eq .Values.tokenConfig.storageType "crd") (not .Values.goinkube.enabled )}}
          livenessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.probe.port }}
              scheme: {{ .Values.probe.scheme }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.probe.port }}
              scheme: {{ .Values.probe.scheme }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.server.port }}
              name: proto
              protocol: TCP
          {{- if eq .Values.tokenConfig.storageType "crd" }}
            - containerPort: {{ .Values.metric.port }}
              name: metrics
              protocol: TCP
          {{- end }}
          {{- with .Values.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
          {{- toYaml . | nindent 12 }}
          {{ end }}
          securityContext:
          {{- if .Values.goinkube.enabled }}
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          {{- else }}
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - "ALL"
          {{- end }}
          volumeMounts:
            - mountPath: /config.yaml
              name: config
              subPath: config.yaml
            {{ if .Values.server.ssl }}
            - mountPath: /tmp/cert/server
              name: server-cert
              readOnly: true
            {{ end }}
            {{ if .Values.goinkube.storage.enabled }}
            - mountPath: /work
              name: work
            {{ end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "sk-auth.serviceAccountName" . }}
      terminationGracePeriodSeconds: 10
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "sk-auth.configName" . }}
        {{ if .Values.server.ssl }}
        - name: server-cert
          secret:
            defaultMode: 420
            secretName: {{ include "sk-auth.certificateSecretName" . }}
        {{ end }}
        {{ if .Values.goinkube.storage.enabled }}
        - name: work
          persistentVolumeClaim:
            claimName: {{ include "sk-auth.fullname" . }}-goinkube
        {{ end }}
