{{ if and .Values.ingress.enabled (eq .Values.ingressClass "nginx") }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "sk-auth.ingressName" . }}
  labels:
    {{- include "sk-auth.labels" . | nindent 4 }}
  annotations:
    # We want flow to be secured up to the end. (This option does not prevent plain HTTP if so configured).
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    {{- with .Values.commonAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ required "ingress.host must be defined!" .Values.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: {{ include "sk-auth.serviceName" . }}
                port:
                  number: {{ .Values.server.port }}
            path: /
            pathType: Prefix
{{ end }}
