{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sk-auth.serviceAccountName" . }}
  labels:
    {{- include "sk-auth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "sk-auth.editorRoleName" . }}"
  namespace: {{  include "sk-auth.tokenNamespace" . }}
  labels:
    {{- include "sk-auth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["session.skasproject.io"]
    resources:
      - tokens
    verbs: ["get", "list", "watch", "delete"]
{{ end }}
