---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sk-auth.serviceName" . }}
  labels:
    {{- include "sk-auth.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    {{- include "sk-auth.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}

