
log:
  mode: dev
  level: info


server:
  ssl: false


providers:
  - name: static
    httpClient:
      url: http://127.0.0.1:7010
#      clientAuth:
#        id: merger
#        secret: 1234
#    groupPattern: "static_%s"
#    credentialAuthority: true
#  - name: crd
#    httpClient:
#      url: http://localhost:7012
#      clientAuth:
#        id: merger
#        secret: 1234


services:
  userStatus:
    clients:
      - id: "*"
        secret: "*"
  userDescribe:
    clients:
      - id: "*"
        secret: "*"
  login:
    clients:
      - id: "*"
        secret: "*"

#  userStatus:
#    enabled: true
#    clients:
#      - id: "test1"
#        secret: "test1"
#  userDescribe:
#    enabled: true
#    clients:
#      - id: "test2"
#        secret: "test2a"
#  login:
#    enabled: true
#    clients:
#      - id: "test2"
#        secret: "test2a"
#      - id: "test3"
#        secret: "abcd"
