
log:
  mode: dev
  level: debug


server:
  ssl: false


providers:
  - name: static
    httpClient:
      url: http://localhost:7010
    groupPattern: "static_%s"
    credentialAuthority: true
    client:
      id: merger
      secret: 1234


services:
  userStatus:
    enabled: true
    clients:
      - id: "test1"
        secret: "test1"
  userDescribe:
    enabled: true
    clients:
      - id: "test2"
        secret: "test2a"
  login:
    enabled: true
    clients:
      - id: "test2"
        secret: "test2a"
      - id: "test3"
        secret: "abcd"

