
log:
  mode: dev
  level: info


server:
  ssl: false


providers:
  - name: static
    httpClient:
      url: http://localhost:7010
      clientAuth:
        id: merger
        secret: 1234
    groupPattern: "static_%s"
    credentialAuthority: true


services:
  userStatus:
    enabled: true
    clients:
      - id: "*"
        secret: "*"
  userDescribe:
    enabled: true
    clients:
      - id: "*"
        secret: "*"
  login:
    enabled: true
    clients:
      - id: "*"
        secret: "*"

#  userStatus:
#    enabled: true
#    clients:
#      - id: "test1"
#        secret: "test1"
#  userDescribe:
#    enabled: true
#    clients:
#      - id: "test2"
#        secret: "test2a"
#  login:
#    enabled: true
#    clients:
#      - id: "test2"
#        secret: "test2a"
#      - id: "test3"
#        secret: "abcd"
