{{- range .Values.generatedSecrets }}
---
apiVersion: "secretgenerator.mittwald.de/v1alpha1"
kind: "StringSecret"
metadata:
  name: {{ .secretName }}
spec:
  fields:
{{- range .fields }}
    - fieldName: {{ .name }}
      encoding: {{ .encoding | default "base64" }}
      length: "{{ .length | default 15 }}"
{{- end }}
{{- end }}


