
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "admin"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nsadmin.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "admins"
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nsadmin.labels" . | nindent 4 }}
subjects:
  - kind: Group
    name: admins
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "admin"

