

replicaCount: 1

# Allow overriding base name of all resources
fullNameOverride:

# Allow chart name overriding
nameOverride:

# Will default to {{ include "skas.fullname" . }}
deploymentName:

# -- Annotations to be added to the pod
podAnnotations: {}

# -- Annotations to be added to all other resources
commonAnnotations: {}


image:
  pullSecrets: []
  repository: ghcr.io/skasproject/skas
  # -- Overrides the image tag whose default is the chart appVersion.
  tag:
  pullPolicy: Always

# Default value. Mau be overridden by component
log:
  mode: dev
  level: info

# Security Context for all containers
commonContainerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - "ALL"

# -- Security Context for the whole pod
podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

# Nodeselector for the pod to be installed
nodeSelector: {}

# -- Tolerations for the pod to be installed
tolerations: []

# -- Affinity for the pod to be installed
affinity: {}

# Cert-manger cluster issuer
clusterIssuer:
# If not provided and <submodule>.exposure.server.ssl == true, then a certificate must be provided externally as a secret. Here is a sample layout:
#
#      apiVersion: v1
#      kind: Secret
#      metadata:
#        name: <deployment>-<static|ldap|crd|merge|auth>-cert
#        namespace: skas-system
#      type: kubernetes.io/tls
#      data:
#        ca.crt: LS0tLS.......
#        tls.crt: LS0tLS.....
#        tls.key: LS0t......
#
# Refer to the documentation for more information about certificate creation

ingressClass: nginx # Don't change, as only 'nginx' is supported for now.

# Base 64 encoded certificate of Root CA. Used to validate all https communication between skas module
rootCaData:

# Kubernetes secrets can be generated automatically. These are intended to be shared between modules for client.id/secret.
# NB: Generation require kubernetes-secret-generator (https://github.com/mittwald/kubernetes-secret-generator) to be deployed in the cluster
generatedSecrets: []
#  - secretName:
#    fields:
#      - name:
#        encoding: base64  # Default: Base 64
#        length: 15

skStatic:
  enabled: false

  log:
    mode:
    level:

  # Will default to {{ include "skas.fullname" . }}-static-config
  configmapName:

  # ConfigMap hosting users and groupBinding. Will default to {{ include "skas.fullname" . }}-users
  usersDbName:

  # Additional arguments to be added to the executable's args list
  additionalArgs: {}

  # Additional env variable definition
  extraEnv: {}

  # Container specific securityContext
  securityContext:

  resources: {}
#    If you want to specify resources, uncomment the following
#    lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#    limits:
#      cpu: 100m
#      memory: 200Mi
#    requests:
#      cpu: 100m
#      memory: 100Mi

  serverPort: 7010

  exposure:
    enabled: false
    clients: []
    ssl: true
    ingress:
      enabled: false
      host:
    # Will default to {{ include "sk-static.fullname" . }}-cert
    certificateSecretName:
    # Will default to {{ include "sk-static.fullname" . }}
    certificateName:
    # Will default to {{ include "sk-static.fullname" . }}
    serviceName:
    # Will default to {{ include "sk-static.fullname" . }}
    ingressName:


  # The users database
  usersDb:
    users: []
    groupBindings: []

skMerge:
  enabled: true

  log:
    mode:
    level:

  # Will default to {{ include "skas.fullname" . }}-static-config
  configmapName:

  # Additional arguments to be added to the executable's args list
  additionalArgs: {}

  # Additional env variable definition
  extraEnv: {}

  # Container specific securityContext
  securityContext:

  resources: {}
  #    If you want to specify resources, uncomment the following
  #    lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #    limits:
  #      cpu: 100m
  #      memory: 200Mi
  #    requests:
  #      cpu: 100m
  #      memory: 100Mi

  serverPort: 7013

  providers:
  #  - name: static
  #    enabled: true
  #    httpClient:
  #      url: https://sk-static1.ingress.kspray1.project33.scw01
  #      rootCaData: "LS0tLS1CRUdJ.........VRFLS0tLS0K"
  #      insecureSkipVerify: false
  #      clientAuth:
  #        id: merger
  #        secret: "1234"
  #    credentialAuthority: true
  #    groupAuthority: true
  #    critical: true
  #    groupPattern: "%s"
  #    uidOffset: 0

  #  - name: ldap1
  #    httpClient:
  #      url: https://sk-ldap1.ingress.kspray1.project33.scw01
  #      clientAuth:
  #        id: merger
  #        secret: "1234"
  #    enabled: true
  #    credentialAuthority: true
  #    critical: true
  #    groupPattern: "ldap_%s"
  #    uidOffset: 10000

  #  - name: crd
  #    httpClient:
  #      url: https://sk-crd1.ingress.kspray1.project33.scw01
  #      clientAuth:
  #        id: merger
  #        secret: "1234"
  #    credentialAuthority: true


  exposure:
    enabled: false
    ssl: true
    ingress:
      enabled: false
      host:
    # Will default to {{ include "sk-merge.fullname" . }}-cert
    certificateSecretName:
    # Will default to {{ include "sk-merge.fullname" . }}
    certificateName:
    # Will default to {{ include "sk-merge.fullname" . }}
    serviceName:
    # Will default to {{ include "sk-merge.fullname" . }}
    ingressName:

    # Provided services
    services:
      login:
        disabled: false
      #   clients:
      #     - id: "*"
      #       secret: "1234"
      userStatus:
        disabled: false
      #   clients:
      #     - id: "*"
      #       secret: "1234"
      userDescribe:
        disabled: false
    #   clients:
    #     - id: "*"
    #       secret: "1234"


