{{ if .Values.skMerge.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skMerge.configmapName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    log:
      mode: {{ default .Values.log.mode .Values.skMerge.log.mode }}
      level: {{ default .Values.log.level .Values.skMerge.log.level }}
    {{ with .Values.rootCaData }}
    rootCaData: {{ . }}
    {{ end }}
    servers:
      {{- if .Values.skMerge.exposure.internal.enabled}}
      - port: {{ .Values.skMerge.exposure.internal.port }}
        interface: "127.0.0.1"
        ssl: false
        services:
          identity:
            disabled: {{ .Values.skMerge.exposure.internal.services.identity.disabled }}
            clients: {{ .Values.skMerge.exposure.internal.services.identity.clients | toJson }}
            protected: {{ .Values.skMerge.exposure.internal.services.identity.protected }}
          passwordChange:
            disabled: {{ .Values.skMerge.exposure.internal.services.passwordChange.disabled }}
            clients: {{ .Values.skMerge.exposure.internal.services.passwordChange.clients | toJson }}
            protected: {{ .Values.skMerge.exposure.internal.services.passwordChange.protected }}
      {{- end }}
      {{- if .Values.skMerge.exposure.external.enabled}}
      - port: {{ .Values.skMerge.exposure.external.port }}
        interface: "0.0.0.0"
        ssl: {{ .Values.skMerge.exposure.external.ssl }}
        {{- if .Values.skMerge.exposure.external.ssl }}
        certDir: /tmp/cert/server
        {{- end }}
        services:
          identity:
            disabled: {{ .Values.skMerge.exposure.external.services.identity.disabled }}
            clients: {{ .Values.skMerge.exposure.external.services.identity.clients  | toJson }}
            protected: {{ .Values.skMerge.exposure.external.services.identity.protected }}
          passwordChange:
            disabled: {{ .Values.skMerge.exposure.external.services.passwordChange.disabled }}
            clients: {{ .Values.skMerge.exposure.external.services.passwordChange.clients  | toJson }}
            protected: {{ .Values.skMerge.exposure.external.services.passwordChange.protected }}
      {{- end }}
    providerInfo:
{{ .Values.skMerge.providerInfo | toYaml | indent 6 }}
    providers:
{{ .Values.skMerge.providers | toYaml | indent 6 }}

{{ end }}

