
{{/*
Expand skStatic container
*/}}
{{- define "container.skStatic" -}}
- name: sk-static
  command:
    - /sk-static
  args:
    - --configFile
    - /config.yaml
    {{-  range .Values.skStatic.additionalArgs }}
    - {{ . }}
    {{- end }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- with .Values.skStatic.extraEnv }}
  env:
  {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.skStatic.resources }}
  resources:
  {{- toYaml . | nindent 12 }}
  {{ end }}
  securityContext:
    {{- toYaml .Values.commonContainerSecurityContext | nindent 12 }}
    {{- with .Values.skStatic.securityContext }}
    {{- toYaml . | nindent 12 }}
    {{- end }}
  ports:
    {{- if .Values.skStatic.exposure.internal.enabled }}
    - containerPort: {{ .Values.skStatic.exposure.internal.port }}
      name: internal
      protocol: TCP
    {{- end }}
    {{- if .Values.skStatic.exposure.external.enabled }}
    - containerPort: {{ .Values.skStatic.exposure.external.port }}
      name: external
      protocol: TCP
    {{- end }}
  volumeMounts:
    - mountPath: /config.yaml
      name: sk-static-config
      subPath: config.yaml
    - mountPath: /users.yaml
      name: sk-static-users
      subPath: users.yaml
    {{ if and .Values.skStatic.exposure.external.enabled .Values.skStatic.exposure.external.ssl }}
    - mountPath: /tmp/cert/server
      name: sk-static-server-cert
      readOnly: true
    {{ end }}
{{- end }}

{{/*
Expand skStatic volumes in pod
*/}}
{{- define "volumes.skStatic" -}}
- name: sk-static-config
  configMap:
    name: {{ include "skStatic.configmapName" . }}
- name: sk-static-users
  configMap:
    name: {{ include "skStatic.usersDbName" . }}
{{- if and .Values.skStatic.exposure.external.enabled .Values.skStatic.exposure.external.ssl }}
- name: sk-static-server-cert
  secret:
    defaultMode: 420
    secretName: {{ include "skStatic.certificateSecretName" . }}
{{- end }}

{{- end }}
