{{ if .Values.skStatic.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skStatic.usersDbName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  users.yaml: |
    {{- if not .Values.skStatic.usersDb.users  }}
    users: []
    {{- end }}
    {{- with .Values.skStatic.usersDb.users }}
    users:
      {{- range . }}
      - {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    {{- if not .Values.skStatic.usersDb.groupBindings  }}
    groupBindings: []
    {{- end }}
    {{- with .Values.skStatic.usersDb.groupBindings }}
    groupBindings:
      {{- range . }}
      - {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
{{ end }}