{{- if .Values.skCrd.enabled }}
{{- if .Values.skCrd.initialUser }}
---
apiVersion: userdb.skasproject.io/v1alpha1
kind: User
metadata:
  name: {{ .Values.skCrd.initialUser.login }}
  namespace: {{ $.Values.skCrd.namespace }}
spec:
{{- with .Values.skCrd.initialUser.commonNames }}
  commonNames:
  {{- toYaml . | nindent 4 }}
{{- end }}
  passwordHash: {{ .Values.skCrd.initialUser.passwordHash }}


{{ range .Values.skCrd.initialUser.groups }}
---
apiVersion: userdb.skasproject.io/v1alpha1
kind: GroupBinding
metadata:
  name: {{ (printf "%s-%s" $.Values.skCrd.initialUser.login .) | replace ":" "-" }}
  namespace: {{ $.Values.skCrd.namespace }}
spec:
  user: {{ $.Values.skCrd.initialUser.login }}
  group: {{ . }}
{{- end }}

{{- end }}
{{- end }}
