
{{/*
Expand skCrd container
*/}}
{{- define "container.skCrd" -}}
- name: sk-crd
  command:
    - /sk-crd
  args:
    - --configFile
    - /config.yaml
    {{-  range .Values.skCrd.additionalArgs }}
    - {{ . }}
    {{- end }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.pullPolicy }}

  livenessProbe:
    httpGet:
      path: /readyz
      port: {{ .Values.skCrd.probe.port }}
      scheme: {{ .Values.skCrd.probe.scheme }}
  readinessProbe:
    httpGet:
      path: /readyz
      port: {{ .Values.skCrd.probe.port }}
      scheme: {{ .Values.skCrd.probe.scheme }}
  {{- with .Values.skCrd.extraEnv }}
  env:
    {{- toYaml . | nindent 12 }}
  {{- end }}
  {{- with .Values.skCrd.resources }}
  resources:
  {{- toYaml . | nindent 12 }}
  {{ end }}
  securityContext:
    {{- toYaml .Values.commonContainerSecurityContext | nindent 12 }}
    {{- with .Values.skCrd.securityContext }}
    {{- toYaml . | nindent 12 }}
    {{- end }}
  ports:
    {{- if .Values.skCrd.exposure.internal.enabled }}
    - containerPort: {{ .Values.skCrd.exposure.internal.port }}
      name: internal
      protocol: TCP
    {{- end }}
    {{- if .Values.skCrd.exposure.external.enabled }}
    - containerPort: {{ .Values.skCrd.exposure.external.port }}
      name: external
      protocol: TCP
    {{- end }}
    - containerPort: {{ .Values.skCrd.metric.port }}
      name: metrics
      protocol: TCP
  volumeMounts:
    - mountPath: /config.yaml
      name: sk-crd-config
      subPath: config.yaml
    {{ if and .Values.skCrd.exposure.external.enabled .Values.skCrd.exposure.external.ssl }}
    - mountPath: /tmp/cert/server
      name: sk-crd-server-cert
      readOnly: true
    {{ end }}
{{- end }}

{{/*
Expand skCrd volumes in pod
*/}}
{{- define "volumes.skCrd" -}}
- name: sk-crd-config
  configMap:
    name: {{ include "skCrd.configmapName" . }}
{{- if and .Values.skCrd.exposure.external.enabled .Values.skCrd.exposure.external.ssl }}
- name: sk-crd-server-cert
  secret:
    defaultMode: 420
    secretName: {{ include "skCrd.certificateSecretName" . }}
{{- end }}

{{- end }}
