{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "sk-userdb.fullname" . }}-editor"
  labels:
    {{- include "sk-userdb.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["userdb.skasproject.io"]
    resources:
      - groupbindings
      - users
    verbs: ["*"]
{{ end }}
