---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sk-crd.configName" . }}
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    namespace: {{ include "sk-crd.userdbNamespace" . }}
    log:
      mode: {{ .Values.log.mode }}
      level: {{ .Values.log.level }}
    metricAddr: ":{{ .Values.metric.port }}"
    probeAddr: ":{{ .Values.probe.port }}"
    server:
      ssl: {{ .Values.server.ssl }}
      bindAddr: ":{{ .Values.server.port}}"
    {{ if .Values.server.ssl }}
      certDir: /tmp/cert/server
    {{ end }}
