{{- if .Values.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sk-crd.serviceAccountName" . }}
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "skas:{{ .Release.Namespace }}-{{ include "sk-crd.fullname" . }}"
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["userdb.skasproject.io"]
    resources:
      - groupbindings
      - users
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "skas:{{ .Release.Namespace }}-{{ include "sk-crd.fullname" . }}-{{ include "sk-crd.serviceAccountName" . }}"
  namespace: {{ .Values.userdbNamespace}}
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sk-crd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "skas:{{ .Release.Namespace }}-{{ include "sk-crd.fullname" . }}"
{{- end }}


