

{{- if and  .Values.rbac.create (eq (include "sk-crd.userdbNamespace" .) .Release.Namespace) }}
# userdb is in same namespace. Use a simple Role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "sk-crd.roleName" . }}"
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["userdb.skasproject.io"]
    resources:
      - groupbindings
      - users
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "sk-crd.roleName" . }}-{{ include "sk-crd.serviceAccountName" . }}"
  labels:
    {{- include "sk-crd.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "sk-crd.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "sk-crd.roleName" . }}"

{{- end }}


