log:
  mode: dev
  level: debug


server:
  ssl: false

ldap:
  host: n0.ipa2
  port: 636
  rootCA: ./cert-ipa2.pem
  bindDN: uid=admin,cn=users,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
  bindPW: adminipa
  userSearch:
    baseDN: cn=users,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
    emailAttr: mail
    filter: (objectClass=inetOrgPerson)
    loginAttr: uid
    numericalIdAttr: uidNumber
    cnAttr: cn
  groupSearch:
    baseDN: cn=groups,cn=accounts,dc=vgr,dc=broadsoftware,dc=com
    filter: (objectClass=posixgroup)
    linkGroupAttr: member
    linkUserAttr: DN
    nameAttr: cn

