
log:
  mode: dev
  level: debug


server:
  ssl: false

ldap:
  host: n0.ldap1
  #port: 389
  insecureNoSSL: false
  bindDN: cn=Manager,dc=odp,dc=com
  bindPW: adminldap
  rootCA: ./ca-odp.crt
  userSearch:
    baseDN: ou=Users,dc=odp,dc=com
    filter: (objectClass=inetOrgPerson)
    loginAttr: uid
    emailAttr: mail
    numericalIdAttr: uidNumber
    cnAttr: cn
  groupSearch:
    baseDN: ou=Groups,dc=odp,dc=com
    filter: (objectClass=posixgroup)
    nameAttr: cn
    linkGroupAttr: memberUid
    linkUserAttr: uid
