
- name: Remove skuser helm chart
  kubernetes.core.helm:
    release_state: absent
    release_name: "{{ skas_users_helm_release }}"
    release_namespace: "{{ skas_namespace}}"
    create_namespace: false
    chart_ref: "{{ skas_users_helm_chart_url }}"
  run_once: true

