{{ if .Values.skStatic.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "skStatic.configmapName" . }}
  labels:
    {{- include "skas.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  config.yaml: |
    log:
      mode: {{ default .Values.log.mode .Values.skStatic.log.mode }}
      level: {{ default .Values.log.level .Values.skStatic.log.level }}
    usersConfigMap: {{ include "skStatic.usersDbName" . }}
    servers:
      {{- if .Values.skStatic.exposure.internal.enabled}}
      - port: {{ .Values.skStatic.exposure.internal.port }}
        interface: "127.0.0.1"
        ssl: false
        services:
          identity:
            disabled: {{ .Values.skStatic.exposure.internal.services.identity.disabled }}
            clients: {{ .Values.skStatic.exposure.internal.services.identity.clients | toJson }}
            protected: {{ .Values.skStatic.exposure.internal.services.identity.protected }}
      {{- end }}
      {{- if .Values.skStatic.exposure.external.enabled}}
      - port: {{ .Values.skStatic.exposure.external.port }}
        interface: "0.0.0.0"
        ssl: {{ .Values.skStatic.exposure.external.ssl }}
        {{- if .Values.skStatic.exposure.external.ssl }}
        certDir: /tmp/cert/server
        {{- end }}
        services:
          identity:
            disabled: {{ .Values.skStatic.exposure.external.services.identity.disabled }}
            clients: {{ .Values.skStatic.exposure.external.services.identity.clients  | toJson }}
            protected: {{ .Values.skStatic.exposure.external.services.identity.protected }}
      {{- end }}

{{ end }}

