

{{- range $name, $value := .Values.bindingByName }}
---
apiVersion: userdb.skasproject.io/v1alpha1
kind: GroupBinding
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "skusers.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  user: {{ $value.user }}
  group: {{ $value.group }}
{{- end }}
