

{{- range $login, $value := .Values.userByLogin }}
---
apiVersion: userdb.skasproject.io/v1alpha1
kind: User
metadata:
  name: {{ $login }}
  namespace: {{ $.Release.Namespace }}
  labels:
      {{- include "skusers.labels" $ | nindent 4 }}
  {{- with $.Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- with $value.commonNames }}
  commonNames:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $value.passwordHash }}
  passwordHash: {{ . }}
{{- end }}
{{- with $value.disabled}}
  disabled: {{ . }}
{{- end }}
{{- with $value.emails }}
  emails:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- with $value.comment}}
  comment: {{ . }}
{{- end }}
{{- with $value.uid}}
  uid: {{ . }}
{{- end }}
{{- end }}
