


metricAddr: "0"
probeAddr: "0"

log:
  mode: dev
  level: trace


server:
  ssl: false

#services:
#  token:
#    disabled: false
#    clients:
#      - id: "*"
#        secret: "*"
#  k8sAuth:
#    disabled: false
#    clients:
#      - id: "*"
#        secret: "*"
#  kubeconfig:
#    disabled: false
#    clients:
#      - id: "*"
#        secret: "*"



loginProvider:
  url: http://127.0.0.1:7013
  clientAuth:
    id: "auth"


tokenConfig:
  inactivityTimeout: "30m"
  sessionMaxTTL: "12h"
  clientTokenTTL: "30s"
  storageType: memory
  lastHitStep: 3
  namespace:


kubeconfig:
  cluster:
    apiServerUrl: https://10.33.0.99:6443
    insecureSkipTLSVerify: true
  user:
    authServerUrl: https://sk-auth.ingress.kspray1.project33.scw01
    insecureSkipVerify: true


