
log:
  mode: dev
  level: trace


server:
  ssl: false

services:
  token:
    enabled: true
    clients:
      - id: "*"
        secret: "*"

loginProvider:
  url: http://127.0.0.1:7013
  clientAuth:
    id: "auth"


tokenConfig:
  inactivityTimeout: "30m"
  sessionMaxTTL: "12h"
  clientTokenTTL: "30s"
  storageType: crd
  lastHitStep: 3
  namespace:
